### ISSUE TITLE
Nothing in sightings about the dev raid incident as seen on the alphaver wiki

### ISSUE THREAD

**Issue by imheavi** [NexTre-dev/alphaver#113]
Just wondering if maybe the images and videos, as well as the conversation, could be added to the repo.

https://alphaver.fandom.com/wiki/The_Dev_Raid_Incident#articleComments

**Comment by HeaviStrawberry** [comment]
wrong link whoops

https://alphaver.fandom.com/wiki/The_Dev_Raid_Incident
