### ISSUE TITLE
Add server to /sightings

### ISSUE THREAD

**Issue by pr1ncess-emily** [NexTre-dev/alphaver#26]
We should add which server the sighting happened on for entries in [/sightings](https://github.com/NexTre-dev/alphaver/tree/main/sightings) for clarification.

**Comment by NexTre-dev** [comment]
didn't they happen on your server?

**Comment by NexTre-dev** [comment]
also, i'm not sure which server they occured on because neither the footage, and the slides from the presentation include that info
if you can expand them, open a pr please :)

**Comment by pr1ncess-emily** [comment]
No problem, all of the sightings from the slides occurred on the private server with Retro and some other people so I can update that, as well as adding whatever stuff happened on my server
