### ISSUE TITLE
Remove the sightings from the todo list

### ISSUE THREAD

**Issue by EzzyUwU** [NexTre-dev/alphaver#41]
Since the sightings are commented out in their section of the readme says they are to be disregarded, 
![image](https://user-images.githubusercontent.com/107564719/173855981-985cff62-2979-4ea8-ac96-5ff47216caa4.png)
shouldn't cross it out or remove it form the list of questions? 
![image](https://user-images.githubusercontent.com/107564719/173856152-07fede9c-d0f3-4ed7-8f1f-5e21b9a831e6.png)

**Comment by NexTre-dev** [comment]
I did actually miss this, as I wasn't focused on the questions (I kinda forgot they exist lol), I'll change this in a bit and only mark sightings that cannot be proved to be legitimate.

**Comment by NexTre-dev** [comment]
I updated the sighting outline, should be a bit more clear now.
