### ISSUE TITLE
New videos surfaced on VidLii

### ISSUE THREAD

**Issue by catauro0** [NexTre-dev/alphaver#65]
Been a while since I've used GitHub, forgot there's an issues section.
### Discussed in https://github.com/NexTre-dev/alphaver/discussions/64

<div type='discussions-op-text'>

<sup>Originally posted by **catauro0** July 18, 2022</sup>
New videos have surfaced on VidLii. Seem to be new. https://www.vidlii.com/user/legoman</div>

**Comment by Kiffolisk** [comment]
looks just like a random dude playing it
