### ISSUE TITLE
OST 2 Album Cover code

### ISSUE THREAD

**Issue by Vladg24YT** [NexTre-dev/alphaver#77]
The `9137 2785` one.

1. It is not mentioned anywhere in the repo.
2. Did anyone find what was it for?

**Comment by Vladg24YT** [comment]
This is the only way I could make the code visible:
![unnamed_modified](https://user-images.githubusercontent.com/35247077/182680769-4fdad9f3-3eb4-4d13-a72a-c2d3a1a94d64.png)

And this is a picture by dotty#7939 from RGN's Discord, who managed to get a better view of the code:
![image](https://user-images.githubusercontent.com/35247077/182681061-b8a987ea-96c0-4da1-acea-e538055caaf8.png)

**Comment by Vladg24YT** [comment]
I don't know how `dotty` managed to get such a good clear view of the code, but I just used color correction

**Comment by NexTre-dev** [comment]
Added by #87
